### ISSUE TITLE
[Project] Scala + 

### ISSUE THREAD

**Issue by minSW** [strange-study/ss-spark#50]
# Spark + Scala + Komoran
> *한국어 형태소 분석기 Komoran : https://docs.komoran.kr/index.html*
> 

정형화되지 않은 커뮤니티 글 특성 상 형태소 분석기가 기대한만큼의 성능 x
일단은 다음과 같은 방법으로 활용

1. 형태소 분석을 사용해 명사 (nouns) 만 추출
2. 추출된 명사가 없는 경우 단순 tokenizer (스페이스 구분) 사용

### Todo
- [x] 1단계 - 데이터 파싱 + 단어 빈도수 구하기
- [x] 2단계 - tf-idf
- [ ] 3단계 - 숨은 의미 분석 
- [ ] 각 갤러리 결과 하나의 dataframe으로 union

### Code

```scala
package com.sw.test

import org.apache.spark.sql.{Dataset, SparkSession}
import org.apache.spark.sql.functions._
import org.apache.spark.ml.feature.{CountVectorizer, IDF, RegexTokenizer}
import org.apache.spark.ml.linalg.SparseVector
import kr.co.shineware.nlp.komoran.constant.DEFAULT_MODEL
import kr.co.shineware.nlp.komoran.core.Komoran
import org.apache.spark.sql.functions.udf
import org.apache.spark.sql.expressions.UserDefinedFunction
import scala.collection.JavaConverters._
import java.io.File

import org.apache.spark.mllib.linalg.distributed.RowMatrix
import org.apache.spark.mllib.linalg.{Vectors, Vector => MLLibVector}
import org.apache.spark.ml.linalg.{Vector => MLVector}


/**
 * @author 민세원
 */

object ProjectApp {
  
  val outputPath: String = "/home/data/output/20210702"
  val numTerms = 10
  
  // FIXME : LIGHT vs FULL
  val komoran = new Komoran(DEFAULT_MODEL.LIGHT)
  
  val getNounsUdf: UserDefinedFunction = udf[Seq[String], String] { sentence => komoran.analyze(sentence).getNouns.asScala }
  
  val tokenizer: RegexTokenizer = new RegexTokenizer().setInputCol("title").setOutputCol("tokens").setPattern("[ ]")

  def main(args: Array[String]): Unit = {
    val spark = SparkSession.builder().appName("Project Application").getOrCreate()

    val outputDir = new File(outputPath)
    val fileList : List[File] = if (outputDir.exists && outputDir.isDirectory) outputDir.listFiles.filter(_.isFile).toList else List[File]()

    for (f <- fileList) {
      val df = spark.read
        .options(Map("header"->"true", "inferSchema"->"true"))
        .csv(f.getPath)
        .withColumn("gall_id", lit(f.getPath.split("/").last.split(".csv")(0)))
      
      val outputDF = tokenizer.transform(df)
        .withColumn("nouns", getNounsUdf(col("title")))
        .select(col("gall_id"), col("title"), when(size(col("nouns")) > 0, col("nouns")).otherwise(col("tokens")).as("terms"))
        .filter(size(col("output")) > 0)
      
      //TF
      val model = new CountVectorizer().setInputCol("terms").setOutputCol("termsFreqs").setVocabSize(numTerms).fit(outputDF)
      val termIds: Array[String] = model.vocabulary

      val docTermsFreqs = model.transform(outputDF)

      docTermsFreqs.cache()


      //IDF
      val idfModel = new IDF().setInputCol("termsFreqs").setOutputCol("tfidfVec").fit(docTermsFreqs)
      val docTermMatrix = idfModel.transform(docTermsFreqs)

      val docRdd = docTermMatrix.select("tfidfVec")
      
      val bestwords = docRdd.flatMap { ele =>
        var idx = -1
        val ids = ele.getAs[SparseVector](0).toDense.toArray.map(value => {
          idx = idx + 1
          (idx, value)
        })
        ids.filter(v => {v._2 == 0.0}).map{v => termIds(v._1)}
      }
      bestwords.select(collect_list("value")).first().getList[String](0) // => {gall_id, words={}}
      // TODO: union
    }

//    // row ID - doc TITLE
//    //val docIds = docTermsFreqs.rdd.map(_.getString(0)).zipWithUniqueId().map(_.swap).collect().toMap
//    
//    // SVD
//    val vecRdd = docTermMatrix.select("tfidfVec").rdd.map{ row => Vectors.fromML(row.getAs[MLVector]("tfidfVec"))}
//    vecRdd.cache()
//    val mat = new RowMatrix(vecRdd)
//    val k = 1000
//    val svd = mat.computeSVD(k, computeU=true)

    }
}

```

**Comment by minSW** [comment]
# 정리
- 대상 데이터
   - Top100 커뮤니티 중, 일일 게시물 제목을 기준으로 추출된 단어 => **컨셉** 추출 (단어 + 커뮤니티명)
   - Tokenize 방식 : komoran 명사 추출 + 일반 Split (" " 단위)
- 추출 데이터
   - `1` TF-IDF
   - `2` top docs for term / `3` top 100 terms (SVD)
- 시각화 대상
   - [x] 1차 - 컨셉으로 묶이는 **커뮤니티 명 그룹핑** 시각화
   - [x] 2차 - 각 컨셉 내에 **점수에 따른 단어 시각화** (word cloud)
   - [x] 3차 - **각 단어 별 연관도 높은 커뮤니티 랭크** 시각화 및 리다이렉트 구현
- 시각화 구현 솔루션
   - https://github.com/strange-study/ss-spark/issues/56#issuecomment-911829631 참고

## 시각화
### ver.0 (Draft)
> react-wordcloud

<img width="400" alt="스크린샷 2021-09-03 오전 12 52 42" src="https://user-images.githubusercontent.com/26691216/138340152-09e94331-07e3-4111-a8cb-4ecad77d21e7.png">

### ver.1 
> [Nivo](https://nivo.rocks/) + react-wordcloud
- 1차
   <img width="400" alt="스크린샷 2021-10-22 오전 2 26 55" src="https://user-images.githubusercontent.com/26691216/138341252-a1396401-699c-4484-8e83-9a5533ea755f.png">
- 2차 
   <img width="400" alt="스크린샷 2021-10-22 오전 2 27 05" src="https://user-images.githubusercontent.com/26691216/138341268-12faf736-7aba-47b1-8ee4-885d5b26a59b.png">
- 3차
   <img width="200" alt="스크린샷 2021-10-22 오전 4 18 03" src="https://user-images.githubusercontent.com/26691216/138342893-f96f667c-711a-438f-83a3-6eec8da5bd06.png"> 
   <img width="200" alt="스크린샷 2021-10-22 오전 4 18 51" src="https://user-images.githubusercontent.com/26691216/138342903-1d07ba58-20c9-4b05-879a-7fc2153fd1e5.png">
